### ISSUE TITLE
App is crashing 

### ISSUE THREAD

**Issue by chigup** [Chivorns/SmartMaterialSpinner#11]
This is my logcat

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.key.myapplication, PID: 23896
    java.lang.ArrayIndexOutOfBoundsException: length=10; index=-2
        at java.util.ArrayList.get(ArrayList.java:439)
        at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:385)
        at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:441)
        at android.widget.ArrayAdapter.getView(ArrayAdapter.java:407)
        at com.chivorn.smartmaterialspinner.SmartMaterialSpinner$HintAdapter.buildView(SmartMaterialSpinner.java:1672)
        at com.chivorn.smartmaterialspinner.SmartMaterialSpinner$HintAdapter.getView(SmartMaterialSpinner.java:1646)
        at android.widget.Spinner.makeView(Spinner.java:712)
        at android.widget.Spinner.layout(Spinner.java:660)
        at android.widget.Spinner.onLayout(Spinner.java:622)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by Chivorns** [comment]
Hi @chigup please check your array item. Base on your log provided, it is ArrayIndexOutOfBoundsException. Please verify on that first if it still having the issue, please let me know.

**Comment by Chivorns** [comment]
Hi @chigup let me close this issue as I think it is from your logic. If you found this issue from my lib, please re-open it with detail error log. Thank
