### ISSUE TITLE
Sample app crashes

### ISSUE THREAD

**Issue by ubarua123** [Chivorns/SmartMaterialSpinner#48]
```
Caused by: java.lang.RuntimeException: Font asset not found fonts/hinted_cello_sans_light.ttf
        at android.graphics.Typeface.createFromAsset(Typeface.java:839)
        at com.chivorn.smartmaterialspinner.SmartMaterialSpinner.initAttributes(SmartMaterialSpinner.java:276)
        at com.chivorn.smartmaterialspinner.SmartMaterialSpinner.init(SmartMaterialSpinner.java:247)
```

**Comment by Chivorns** [comment]
Thank @ubarua123 , I will check it soon. Is it the app from Play Store?

**Comment by ubarua123** [comment]
No.. I cloned the repo and ran it

**Comment by Chivorns** [comment]
Hi @ubarua123 , I found it now. It error only if you run with Kotlin module. let me update it

**Comment by Chivorns** [comment]
Hi @ubarua123 , I already pushed the latest source code to repo. Please review. Thank for your feedback.
