### ISSUE TITLE
App crashes when you start typing while spinner is scrolling

### ISSUE THREAD

**Issue by Adelina609** [Chivorns/SmartMaterialSpinner#53]
**Steps to reproduce:**
select an item in code using spinner.setSelection(position)
click on spinner for selecting item(spinner starts scrolling), in that moment you should start typing something in search.

Also, count of items ~1500

**Logs**
`java.lang.IndexOutOfBoundsException: setSpan (-1 ... 1) starts before 0
        at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:496)
        at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:196)
        at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:183)
        at android.text.SpannableString.setSpan(SpannableString.java:60)
        at com.chivorn.smartmaterialspinner.SearchableSpinnerDialog$1.getView(SearchableSpinnerDialog.java:209)
        at android.widget.AbsListView.obtainView(AbsListView.java:2494)
        at android.widget.HwAbsListView.obtainView(HwAbsListView.java:1139)
        at android.widget.ListView.makeAndAddView(ListView.java:2119)
        at android.widget.ListView.fillDown(ListView.java:815)
        at android.widget.ListView.fillGap(ListView.java:776)
        at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5646)
        at android.widget.ListView.trackMotionScroll(ListView.java:2013)
        at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:5152)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
        at android.view.Choreographer.doCallbacks(Choreographer.java:875)
        at android.view.Choreographer.doFrame(Choreographer.java:772)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)`

**Comment by KaihuaiX** [comment]
got the same issue.

**Comment by MarcellHarmaci** [comment]
Same issue here.
