### ISSUE TITLE
Crash ao realizar pesquisa 

### ISSUE THREAD

**Issue by YASMINCOS** [Chivorns/SmartMaterialSpinner#70]
eu recebo o seguinte erro: 

                                                                                                    java.lang.IndexOutOfBoundsException: setSpan (-1 ... 2) starts before 0
                                                                                                    	at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:478)
                                                                                                    	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:189)
                                                                                                    	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:178)
                                                                                                    	at android.text.SpannableString.setSpan(SpannableString.java:60)
                                                                                                    	at com.chivorn.smartmaterialspinner.SearchableSpinnerDialog$1.getView(SearchableSpinnerDialog.java:222)
                                                                                                    	at android.widget.AbsListView.obtainView(AbsListView.java:3219)
                                                                                                    	at android.widget.ListView.measureHeightOfChildren(ListView.java:1451)
                                                                                                    	at android.widget.ListView.onMeasure(ListView.java:1358)
                                                                                                    	at android.view.View.measure(View.java:25056)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7745)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
                                                                                                    	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1187)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:706)
                                                                                                    	at android.view.View.measure(View.java:25056)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7745)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
                                                                                                    	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
                                                                                                    	at android.view.View.measure(View.java:25056)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7745)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
                                                                                                    	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
                                                                                                    	at android.view.View.measure(View.java:25056)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7745)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                                    	at android.view.View.measure(View.java:25056)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7745)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                                    	at android.view.View.measure(View.java:25056)
                                                                                                    	at com.android.internal.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:144)
                                                                                                    	at com.android.internal.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:69)
                                                                                                    	at android.view.View.measure(View.java:25056)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7745)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                                    	at android.view.View.measure(View.java:25056)

**Comment by ahmad-imran15** [comment]
have this issue resolved?
